### ISSUE TITLE
UTR from canonical transcript

### ISSUE THREAD

**Issue by Amokelani** [ImperialCardioGenetics/UTRannotator#10]
Good day,
I wanted to ask when prioritising high impact 5'UTR do you only consider those in canonical transcript or do you also assess transcript expression? I have found that majority (almost all) 5'UTR found in our cohort are not in canonical transcript I checked one of the variant it was not in the genes canonical transcript but it does seem that the transcript is expressed in relevant tissue for disease. I am not sure if I should discount all the other 5'UTR because they are not in canonical transcripts

**Comment by nickywhiff** [comment]
Hi, UTRannotator will annotate a variant with respect to all transcripts where it has an annotation of '5_prime_UTR_variant' from VEP. You should therefore be able to select a transcript that is different from the 'canonical'. There are no annotations that take into account transcript expression. Of note, the definition of 'canonical', which can differ across resources, may not account for expression (i.e. it may be as simple as taking the longest coding sequence) and hence it may be appropriate to use annotations on different transcripts, however, as this is gene/tissue/context dependent I cannot give advice.
