### ISSUE TITLE
Compatibility issues with GEMINI again

### ISSUE THREAD

**Issue by karynne7** [ImperialCardioGenetics/UTRannotator#3]
In your previous annotator, I had problems using with GEMINI for the "From" pieces in the output. This time I am seeing that "From" and a bunch of additional "=" that also do not play nicely with loading into GEMINI. 

I can work around it, but I assume others will have issues if that is their plan as well. 

Or if you have suggestions outside of simple sed statements, I'm all ears. Thanks.

**Comment by XiaoleiZ** [comment]
Thanks for your suggestions! 

I've updated the output form: changing the names with "From" and replacing "=" with ":".  

It works well with VEP default output, tab-delimited output and VCF output now! Have a check.

**Comment by karynne7** [comment]
This works great for me, thank you so much!

**Comment by XiaoleiZ** [comment]
Great to hear!
