### ISSUE TITLE
the plugin does not work with --cache

### ISSUE THREAD

**Issue by shadrinams** [ImperialCardioGenetics/UTRannotator#4]
Hello ,
I started to use the UTRannotator but when I run it offline I get empty fields from the UTRannotator. With --database, it works fine. Could you tell me please what could be wrong? Thank you!

**with --offline:**
`vep -i 5_prime_UTR.dnvs.vcf --cache --dir_cache $pathToCache_GR37 --offline --minimal --dir_plugins /sc/hydra/work/shadrm01/UTRannotator-master/ --plugin UTRannotator,../uORF_starts_ends_GRCh37_PUBLIC.txt --tab --force_overwrite -o UTRannotator.cache.out

#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	ALLELE_NUM	IMPACT	DISTANCE	STRAND	FLAGS	MINIMISED	existing_InFrame_oORFs	existing_OutOfFrame_oORFs	existing_uORFs	five_prime_UTR_variant_annotation	five_prime_UTR_variant_consequence
**19_3785169_C/T	19:3785169	T	ENSG00000007264	ENST00000310132	Transcript	5_prime_UTR_variant	364	-	-	-	-	-	1	MODIFIER	-	-1	-	1	0	0	0	-	-**
19_3785169_C/T	19:3785169	T	ENSG00000007264	ENST00000395040	Transcript	intron_variant	-	-	-	-	-	-	1	MODIFIER	-	-1	-	1	-	-	-	-	-
19_3785169_C/T	19:3785169	T	ENSG00000007264	ENST00000395045	Transcript	intron_variant	-	-	-	-	-	-	1	MODIFIER	-	-1	-	1	-	-	-	-	-`

**with --database:**
`vep -i 5_prime_UTR.dnvs.vcf --database --port 3337 --dir_plugins /sc/hydra/work/shadrm01/UTRannotator-master/ --plugin UTRannotator,../uORF_starts_ends_GRCh38_PUBLIC.txt --tab --force_overwrite -o UTRannotator.database.out

#Uploaded_variation	Location	Allele	Gene	Feature	Feature_type	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	IMPACT	DISTANCE	STRAND	FLAGS	existing_InFrame_oORFs	existing_OutOfFrame_oORFs	existing_uORFs	five_prime_UTR_variant_annotation	five_prime_UTR_variant_consequence
**19_3785169_C/T	19:3785169	T	ENSG00000007264	ENST00000310132	Transcript	5_prime_UTR_variant	364	-	-	-	-	-	MODIFIER	-	-1	-	0	0	1	uAUG_gained_CapDistanceToStart:363,uAUG_gained_DistanceToCDS:36,uAUG_gained_DistanceToStop:1557,uAUG_gained_KozakContext:AGTATGC,uAUG_gained_KozakStrength:Moderate,uAUG_gained_type:inFrame_oORF	uAUG_gained**
19_3785169_C/T	19:3785169	T	ENSG00000007264	ENST00000395040	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	-1	-	-	-	-	-	-
19_3785169_C/T	19:3785169	T	ENSG00000007264	ENST00000395045	Transcript	intron_variant	-	-	-	-	-	-	MODIFIER	-	-1	-	-	-	-	-	-

`

**Comment by XiaoleiZ** [comment]
Hi sorry it took me so long to reply. 
The issue shall be solved if you add the reference genome in vep command: `--fasta /path/to/reference_genome`

**Comment by NLSVTN** [comment]
I just had the same issue and it was fixed by the provided solution.

**Comment by NLSVTN** [comment]
It runs as an ipython job, but not as a spark one giving me an error:

```
Hail version: 0.2.26-3a68be23cb82

Error summary: HailException: VEP command ‘/vep/ensembl-tools-release-99/vep --format vcf --json --everything --allele_number --no_stats --cache --offline --fasta /vep/loftee_data_grch38/human_ancestor.fa --minimal --verbose --assembly GRCh38 --dir_cache /vep/vep_cache --plugin UTRannotator,LoF,human_ancestor_fa:/vep/loftee_data_grch38/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15,conservation_file:/vep/loftee_data_grch38/loftee.sql,loftee_path:/vep/loftee_grch38,gerp_bigwig:/vep/loftee_data_grch38/gerp_conservation_scores.homo_sapiens.GRCh38.bw,run_splice_predictions:0 --dir_plugins /vep/loftee_grch38 -o STDOUT’ failed with non-zero exit status 25
```

I also posted the question here: https://discuss.hail.is/t/utrannotator-in-hails-vep-is-not-shown-in-transcript-consequences-field/1739/7

**Comment by NLSVTN** [comment]
Its an issue of multiple workers running in Hail - VEP. With one worker its fine. Not a file permissions issue.

**Comment by XiaoleiZ** [comment]
I'm going to close this issue now. If you have any other questions please feel free to reopen it.
