### ISSUE TITLE
Use of uninitialized value in split at *.pl line 24, <__ANONIO__> line 4810

### ISSUE THREAD

**Issue by KalinNonchev** [ImperialCardioGenetics/UTRannotator#6]
Hello,

thank you for the plugin. 

I run the UTRannotator like:
`vep -i variants_5utr_0.005_90_10.vcf --cache --tab --assembly GRCh37 --fasta fasta --dir=.../cachedir --offline --plugin UTRannotator,
../UTRannotator/uORF_5UTR_GRCh37_PUBLIC.txt -o variants_5utr_0.005_90_10.utrannotator.tsv `

However, I am getting

```
Possible precedence issue with control flow operator at .../lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
Use of uninitialized value in split at UTRannotator/src/uAUG_gained.pl line 24, <__ANONIO__> line 4810.
Use of uninitialized value in split atUTRannotator/src/uSTOP_lost.pl line 37, <__ANONIO__> line 4810.Use of uninitialized value in split at UTRannotator/src/uAUG_lost.pl line 33, <__ANONIO__> line 4810.
Use of uninitialized value in split at UTRannotator/src/uSTOP_gained.pl line 25, <__ANONIO__> line 4810.
Use of uninitialized value in split at UTRannotator/src/uframeshift.pl line 26, <__ANONIO__> line 4810.
Use of uninitialized value in split at UTRannotator/src/uAUG_gained.pl line 24, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uSTOP_lost.pl line 37, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uAUG_lost.pl line 33, <__ANONIO__> line 26798.
Use of uninitialized value in split atUTRannotator/src/uSTOP_gained.pl line 25, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uframeshift.pl line 26, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uAUG_gained.pl line 24, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uSTOP_lost.pl line 37, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uAUG_lost.pl line 33, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uSTOP_gained.pl line 25, <__ANONIO__> line 26798.
Use of uninitialized value in split at UTRannotator/src/uframeshift.pl line 26, <__ANONIO__> line 26798.
```

It terminates successfully. However, I am not sure what is going on and if the output is correct.

Do you have a suggestion?

Thank you in advance!

Best,

**Comment by XiaoleiZ** [comment]
Sorry about late reply. It would be best if you could provide some sample input variants that cause the warning? 

Thank you.

**Comment by KalinNonchev** [comment]
I am annotating thousands of variants so it is hard for me to identify the exact variant from the input.
Maybe you can give me some hints about what I should look for? 
All my variants are SNVs on the standard chromosomes, so I don't see why there could be a problem on my side?
Can you explain the warning?

**Comment by XiaoleiZ** [comment]
It shouldn't affect the output.

For the first warning msg, it is due to BioPerl (https://github.com/Ensembl/ensembl-vep/issues/914)

For the second one, I checked the lines raising the warnings. I don't see it could affect the output either.

**Comment by KalinNonchev** [comment]
Thanks for the answer. I also investigated the output and it looked all right.
I am closing the issue.
