### ISSUE TITLE
uAUG in-frame/out-of-frame

### ISSUE THREAD

**Issue by KalinNonchev** [ImperialCardioGenetics/UTRannotator#8]
Hi UTRAnnotator team,

is it somehow possible to understand if the uAUG gain/lost was in frame or out-of-frame? 
This could be a really valuable feature.

Best

**Comment by KalinNonchev** [comment]
The type of of 5’ UTR ORF created, described by one of the following: uORF(with a stop codon in 5’UTR), inframe_oORF (inframe and overlapping with CDS),OutOfFrame_oORF (out of frame and overlapping with CDS)

- here it is inframe AND overlapping with CDS, right?

so basically, we don't know if the uAUG is just in- or out-of-frame?

**Comment by jamesware** [comment]
So - to check that I understand, you would like to know whether a (new or existing) uORF that does NOT overlap with the coding sequence is "in frame" with the downstream coding sequence?
On the one hand, this could be confusing - a self-contained uORF that has a stop upstream of the canonical start is not intrinsically "out-of-frame". it is, by definition, a valid "open reading frame".  Furthermore, if the stop is lost then it will become an overlapping oORF, and the annotator will then indicate whether in frame or out of frame wrt the coding sequence.
However, I can see that it might be helpful to know whether the uORF reading frame and CDS reading frame are concordant / in phase, in case the uORF stop is leaky etc.
If you can please confirm that I've understood what you are looking for then the team can discuss.

**Comment by KalinNonchev** [comment]
Exactly - the information if the uORF is in-frame or out-of-frame with the CDS reading frame would be important when investigating the impact of a uAUG gain/lost.
For example, I am expecting that if I have a uAUG gain (in-frame) between the 5'-cap and the canonical start of the main ORF, this would initialize the translation and eventually trigger the NMD machinery.

I agree about the uSTOP.

**So, I would like to know if the uORF and the CDS are concordant/ in phase.**

I hope it is clear now.

**Comment by XiaoleiZ** [comment]
To infer whether an uAUG is inframe or out-of-frame, you can use the distance of uAUG to CDS. If it can be divided by 3, then in-frame otherwise out-of-frame.

**Comment by KalinNonchev** [comment]
yes, this what I need
